#security:
#    role_hierarchy:
#        ROLE_ADMIN:       ROLE_USER
#        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
#   
#    firewalls:
#        dev:
#            pattern:  ^/(_(profiler|wdt)|css|images|js)/
#            security: false
#        
#        secured_area:
#            pattern:    ^/
#            anonymous: ~
#            form_login:
#                login_path:  /login
#                check_path:  /login_check
#                default_target_path: EnsJobeetBundle_homepage
#   
#    access_control:
#        - { path: ^/admin, roles: ROLE_ADMIN }
#   
#    providers:
#        in_memory:
#            memory:
#                users:
#                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }
#    
#    encoders:
#        Symfony\Component\Security\Core\User\User: plaintext

jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        in_memory:
            memory:
                users:
                    admin: { password: adminpass, roles: 'ROLE_ADMIN' }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/demo/secured/login$
            security: false

        secured_area:
            pattern: ^/         
            #/demo/secured/
            anonymous: ~ 
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: EnsJobeetBundle_homepage
            logout:
                path:   _demo_logout
                target: _demo
            #anonymous: ~
            http_basic:
                realm: "Secured Demo Area"

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }

